"""Local retrieval-augmented generation components for GeoPilot."""

from geopilot.rag.chunker import (
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    chunk_knowledge_documents,
)
from geopilot.rag.embeddings import (
    DEFAULT_EMBEDDING_MODEL,
    EmbeddingError,
    EmbeddingErrorCode,
    EmbeddingProvider,
    FastEmbedProvider,
    TokenCounter,
)
from geopilot.rag.evaluation import evaluate_retrieval, load_evaluation_cases
from geopilot.rag.experiment import (
    DEFAULT_CHUNKING_VARIANTS,
    run_chunking_experiment,
)
from geopilot.rag.hybrid import (
    DEFAULT_HYBRID_CANDIDATE_K,
    DEFAULT_RRF_K,
    HybridSearcher,
)
from geopilot.rag.lexical import (
    DEFAULT_BM25_B,
    DEFAULT_BM25_K1,
    BM25Index,
    BM25SearchHit,
    tokenize_for_bm25,
)
from geopilot.rag.loader import (
    KnowledgeLoadError,
    KnowledgeLoadErrorCode,
    load_knowledge_document,
    load_knowledge_documents,
)
from geopilot.rag.models import (
    ChunkingExperimentResult,
    ChunkingExperimentRun,
    ChunkingExperimentVariant,
    IndexedKnowledgeChunk,
    KnowledgeBuildResult,
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeSearchHit,
    KnowledgeSearchResult,
    RelevantKnowledgeTarget,
    RerankExperimentResult,
    RetrievalCaseResult,
    RetrievalEvaluationCase,
    RetrievalEvaluationResult,
    RetrievalExperimentResult,
    RetrievalExperimentRun,
    RetrievalMode,
    StoredVectorIndex,
    TokenUsageStatistics,
    VectorIndexManifest,
)
from geopilot.rag.rerank_experiment import run_rerank_experiment
from geopilot.rag.reranking import (
    DEFAULT_RERANK_CANDIDATE_K,
    DEFAULT_RERANKER_MODEL,
    FastEmbedReranker,
    Reranker,
    RerankerError,
    RerankerErrorCode,
    RerankSearcher,
)
from geopilot.rag.retrieval_experiment import run_retrieval_experiment
from geopilot.rag.service import (
    DEFAULT_KNOWLEDGE_INDEX,
    DEFAULT_MODEL_CACHE,
    DEFAULT_RERANKER_CACHE,
    DEFAULT_RETRIEVAL_MODE,
    KnowledgeRetriever,
    build_knowledge_index,
    open_knowledge_retriever,
)
from geopilot.rag.tokenization import (
    DEFAULT_TOKEN_WARNING_RATIO,
    summarize_token_usage,
)
from geopilot.rag.vector_store import (
    LocalVectorStore,
    VectorStoreError,
    VectorStoreErrorCode,
)

__all__ = [
    "DEFAULT_BM25_B",
    "DEFAULT_BM25_K1",
    "DEFAULT_CHUNKING_VARIANTS",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_HYBRID_CANDIDATE_K",
    "DEFAULT_KNOWLEDGE_INDEX",
    "DEFAULT_MODEL_CACHE",
    "DEFAULT_RERANKER_CACHE",
    "DEFAULT_RERANKER_MODEL",
    "DEFAULT_RERANK_CANDIDATE_K",
    "DEFAULT_RETRIEVAL_MODE",
    "DEFAULT_RRF_K",
    "DEFAULT_TOKEN_WARNING_RATIO",
    "BM25Index",
    "BM25SearchHit",
    "ChunkingExperimentResult",
    "ChunkingExperimentRun",
    "ChunkingExperimentVariant",
    "EmbeddingError",
    "EmbeddingErrorCode",
    "EmbeddingProvider",
    "FastEmbedProvider",
    "FastEmbedReranker",
    "HybridSearcher",
    "IndexedKnowledgeChunk",
    "KnowledgeBuildResult",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeLoadError",
    "KnowledgeLoadErrorCode",
    "KnowledgeRetriever",
    "KnowledgeSearchHit",
    "KnowledgeSearchResult",
    "LocalVectorStore",
    "RelevantKnowledgeTarget",
    "RerankExperimentResult",
    "RerankSearcher",
    "Reranker",
    "RerankerError",
    "RerankerErrorCode",
    "RetrievalCaseResult",
    "RetrievalEvaluationCase",
    "RetrievalEvaluationResult",
    "RetrievalExperimentResult",
    "RetrievalExperimentRun",
    "RetrievalMode",
    "StoredVectorIndex",
    "TokenCounter",
    "TokenUsageStatistics",
    "VectorIndexManifest",
    "VectorStoreError",
    "VectorStoreErrorCode",
    "build_knowledge_index",
    "chunk_knowledge_documents",
    "evaluate_retrieval",
    "load_evaluation_cases",
    "load_knowledge_document",
    "load_knowledge_documents",
    "open_knowledge_retriever",
    "run_chunking_experiment",
    "run_rerank_experiment",
    "run_retrieval_experiment",
    "summarize_token_usage",
    "tokenize_for_bm25",
]
